// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Applies search criteria to an item and refreshes metadata.
    static public func applySearchCriteria(itemID: String, isReplaceAllImages: Bool? = nil, _ body: JellyfinAPI.RemoteSearchResult) -> Request<Void> {
        Request(method: "POST", url: "/Items/RemoteSearch/Apply/\(itemID)", query: makeApplySearchCriteriaQuery(isReplaceAllImages), body: body, id: "ApplySearchCriteria")
    }

    private static func makeApplySearchCriteriaQuery(_ isReplaceAllImages: Bool?) -> [(String, String?)] {
        let encoder = URLQueryEncoder()
        encoder.encode(isReplaceAllImages, forKey: "replaceAllImages")
        return encoder.items
    }
}
