// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Authenticates a user by name.
    static public func authenticateUserByName(_ body: JellyfinAPI.AuthenticateUserByName) -> Request<JellyfinAPI.AuthenticationResult> {
        Request(method: "POST", url: "/Users/AuthenticateByName", body: body, id: "AuthenticateUserByName")
    }
}
