// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Authenticates a user.
    static public func authenticateUser(userID: String, pw: String, password: String? = nil) -> Request<JellyfinAPI.AuthenticationResult> {
        Request(method: "POST", url: "/Users/\(userID)/Authenticate", query: makeAuthenticateUserQuery(pw, password), id: "AuthenticateUser")
    }

    private static func makeAuthenticateUserQuery(_ pw: String, _ password: String?) -> [(String, String?)] {
        let encoder = URLQueryEncoder()
        encoder.encode(pw, forKey: "pw")
        encoder.encode(password, forKey: "password")
        return encoder.items
    }
}
