// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Delete a custom splashscreen.
    static public var deleteCustomSplashscreen: Request<Void> {
        Request(method: "DELETE", url: "/Branding/Splashscreen", id: "DeleteCustomSplashscreen")
    }
}
