// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Downloads a remote image for an item.
    static public func downloadRemoteImage(itemID: String, parameters: DownloadRemoteImageParameters) -> Request<Void> {
        Request(method: "POST", url: "/Items/\(itemID)/RemoteImages/Download", query: parameters.asQuery, id: "DownloadRemoteImage")
    }

    public struct DownloadRemoteImageParameters {
        /// Enum ImageType.
        public var type: `Type`
        public var imageURL: String?

        public typealias `Type` = JellyfinAPI.ImageType

        public init(type: `Type`, imageURL: String? = nil) {
            self.type = type
            self.imageURL = imageURL
        }

        public var asQuery: [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(type, forKey: "type")
            encoder.encode(imageURL, forKey: "imageUrl")
            return encoder.items
        }
    }
}
