// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Gets the configuration pages.
    static public func getConfigurationPages(enableInMainMenu: Bool? = nil) -> Request<[JellyfinAPI.ConfigurationPageInfo]> {
        Request(method: "GET", url: "/web/ConfigurationPages", query: makeGetConfigurationPagesQuery(enableInMainMenu), id: "GetConfigurationPages")
    }

    private static func makeGetConfigurationPagesQuery(_ enableInMainMenu: Bool?) -> [(String, String?)] {
        let encoder = URLQueryEncoder()
        encoder.encode(enableInMainMenu, forKey: "enableInMainMenu")
        return encoder.items
    }
}
