// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Downloads item media.
    static public func getDownload(itemID: String) -> Request<Data> {
        Request(method: "GET", url: "/Items/\(itemID)/Download", id: "GetDownload")
    }
}
