// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Gets a server icon.
    static public func getIconID(serverID: String, fileName: String) -> Request<Data> {
        Request(method: "GET", url: "/Dlna/\(serverID)/icons/\(fileName)", id: "GetIconId")
    }
}
