// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Gets available lineups.
    static public func getLineups(parameters: GetLineupsParameters? = nil) -> Request<[JellyfinAPI.NameIDPair]> {
        Request(method: "GET", url: "/LiveTv/ListingProviders/Lineups", query: parameters?.asQuery, id: "GetLineups")
    }

    public struct GetLineupsParameters {
        public var id: String?
        public var type: String?
        public var location: String?
        public var country: String?

        public init(id: String? = nil, type: String? = nil, location: String? = nil, country: String? = nil) {
            self.id = id
            self.type = type
            self.location = location
            self.country = country
        }

        public var asQuery: [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(id, forKey: "id")
            encoder.encode(type, forKey: "type")
            encoder.encode(location, forKey: "location")
            encoder.encode(country, forKey: "country")
            return encoder.items
        }
    }
}
