// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Gets subtitles in a specified format.
    static public func getSubtitle(routeItemID: String, routeMediaSourceID: String, routeIndex: Int, routeFormat: String, parameters: GetSubtitleParameters? = nil) -> Request<String> {
        Request(method: "GET", url: "/Videos/\(routeItemID)/\(routeMediaSourceID)/Subtitles/\(routeIndex)/Stream.\(routeFormat)", query: parameters?.asQuery, id: "GetSubtitle")
    }

    public struct GetSubtitleParameters {
        public var itemID: String?
        public var mediaSourceID: String?
        public var index: Int?
        public var format: String?
        public var endPositionTicks: Int?
        public var isCopyTimestamps: Bool?
        public var isAddVttTimeMap: Bool?
        public var startPositionTicks: Int?

        public init(itemID: String? = nil, mediaSourceID: String? = nil, index: Int? = nil, format: String? = nil, endPositionTicks: Int? = nil, isCopyTimestamps: Bool? = nil, isAddVttTimeMap: Bool? = nil, startPositionTicks: Int? = nil) {
            self.itemID = itemID
            self.mediaSourceID = mediaSourceID
            self.index = index
            self.format = format
            self.endPositionTicks = endPositionTicks
            self.isCopyTimestamps = isCopyTimestamps
            self.isAddVttTimeMap = isAddVttTimeMap
            self.startPositionTicks = startPositionTicks
        }

        public var asQuery: [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(itemID, forKey: "itemId")
            encoder.encode(mediaSourceID, forKey: "mediaSourceId")
            encoder.encode(index, forKey: "index")
            encoder.encode(format, forKey: "format")
            encoder.encode(endPositionTicks, forKey: "endPositionTicks")
            encoder.encode(isCopyTimestamps, forKey: "copyTimestamps")
            encoder.encode(isAddVttTimeMap, forKey: "addVttTimeMap")
            encoder.encode(startPositionTicks, forKey: "startPositionTicks")
            return encoder.items
        }
    }
}
