// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Upload a document.
    static public func logFile(_ body: String? = nil) -> Request<JellyfinAPI.ClientLogDocumentResponseDto> {
        Request(method: "POST", url: "/ClientLog/Document", body: body, id: "LogFile")
    }
}
