// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Sets the user image.
    static public func postUserImage(userID: String, imageType: String, index: Int? = nil, _ body: Data? = nil) -> Request<Void> {
        Request(method: "POST", url: "/Users/\(userID)/Images/\(imageType)", query: makePostUserImageQuery(index), body: body, id: "PostUserImage")
    }

    private static func makePostUserImageQuery(_ index: Int?) -> [(String, String?)] {
        let encoder = URLQueryEncoder()
        encoder.encode(index, forKey: "index")
        return encoder.items
    }
}
