// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Remove a media path.
    static public func removeMediaPath(parameters: RemoveMediaPathParameters? = nil) -> Request<Void> {
        Request(method: "DELETE", url: "/Library/VirtualFolders/Paths", query: parameters?.asQuery, id: "RemoveMediaPath")
    }

    public struct RemoveMediaPathParameters {
        public var name: String?
        public var path: String?
        public var isRefreshLibrary: Bool?

        public init(name: String? = nil, path: String? = nil, isRefreshLibrary: Bool? = nil) {
            self.name = name
            self.path = path
            self.isRefreshLibrary = isRefreshLibrary
        }

        public var asQuery: [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(name, forKey: "name")
            encoder.encode(path, forKey: "path")
            encoder.encode(isRefreshLibrary, forKey: "refreshLibrary")
            return encoder.items
        }
    }
}
