// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Reports that a session is viewing an item.
    static public func reportViewing(sessionID: String? = nil, itemID: String) -> Request<Void> {
        Request(method: "POST", url: "/Sessions/Viewing", query: makeReportViewingQuery(sessionID, itemID), id: "ReportViewing")
    }

    private static func makeReportViewingQuery(_ sessionID: String?, _ itemID: String) -> [(String, String?)] {
        let encoder = URLQueryEncoder()
        encoder.encode(sessionID, forKey: "sessionId")
        encoder.encode(itemID, forKey: "itemId")
        return encoder.items
    }
}
