// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Sets the enabled and existing package repositories.
    static public func setRepositories(_ body: [JellyfinAPI.RepositoryInfo]) -> Request<Void> {
        Request(method: "POST", url: "/Repositories", body: body, id: "SetRepositories")
    }
}
