// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Sets notifications as unread.
    static public func setUnread(userID: String) -> Request<Void> {
        Request(method: "POST", url: "/Notifications/\(userID)/Unread", id: "SetUnread")
    }
}
