// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Start specified task.
    static public func startTask(taskID: String) -> Request<Void> {
        Request(method: "POST", url: "/ScheduledTasks/Running/\(taskID)", id: "StartTask")
    }
}
