// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    /// Unmarks item as a favorite.
    static public func unmarkFavoriteItem(userID: String, itemID: String) -> Request<JellyfinAPI.UserItemDataDto> {
        Request(method: "DELETE", url: "/Users/\(userID)/FavoriteItems/\(itemID)", id: "UnmarkFavoriteItem")
    }
}
