//
// AdminNotificationDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The admin notification dto. */
public struct AdminNotificationDto: Codable, Hashable {

    /** Gets or sets the notification name. */
    public var name: String?
    /** Gets or sets the notification description. */
    public var description: String?
    public var notificationLevel: NotificationLevel?
    /** Gets or sets the notification url. */
    public var url: String?

    public init(name: String? = nil, description: String? = nil, notificationLevel: NotificationLevel? = nil, url: String? = nil) {
        self.name = name
        self.description = description
        self.notificationLevel = notificationLevel
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case description = "Description"
        case notificationLevel = "NotificationLevel"
        case url = "Url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: CodingKeys.self)
        try encoderContainer.encodeIfPresent(name, forKey: .name)
        try encoderContainer.encodeIfPresent(description, forKey: .description)
        try encoderContainer.encodeIfPresent(notificationLevel, forKey: .notificationLevel)
        try encoderContainer.encodeIfPresent(url, forKey: .url)
    }
}
