//
// AllThemeMediaResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AllThemeMediaResult: Codable, JSONEncodable, Hashable {

    public var themeVideosResult: AllThemeMediaResultThemeVideosResult?
    public var themeSongsResult: AllThemeMediaResultThemeVideosResult?
    public var soundtrackSongsResult: AllThemeMediaResultThemeVideosResult?

    public init(themeVideosResult: AllThemeMediaResultThemeVideosResult? = nil, themeSongsResult: AllThemeMediaResultThemeVideosResult? = nil, soundtrackSongsResult: AllThemeMediaResultThemeVideosResult? = nil) {
        self.themeVideosResult = themeVideosResult
        self.themeSongsResult = themeSongsResult
        self.soundtrackSongsResult = soundtrackSongsResult
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case themeVideosResult = "ThemeVideosResult"
        case themeSongsResult = "ThemeSongsResult"
        case soundtrackSongsResult = "SoundtrackSongsResult"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: CodingKeys.self)
        try encoderContainer.encodeIfPresent(themeVideosResult, forKey: .themeVideosResult)
        try encoderContainer.encodeIfPresent(themeSongsResult, forKey: .themeSongsResult)
        try encoderContainer.encodeIfPresent(soundtrackSongsResult, forKey: .soundtrackSongsResult)
    }
}
