//
// ControlResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ControlResponse: Codable, Hashable {

    public var headers: [String: String]?
    public var xml: String?
    public var isSuccessful: Bool?

    public init(headers: [String: String]? = nil, xml: String? = nil, isSuccessful: Bool? = nil) {
        self.headers = headers
        self.xml = xml
        self.isSuccessful = isSuccessful
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case headers = "Headers"
        case xml = "Xml"
        case isSuccessful = "IsSuccessful"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: CodingKeys.self)
        try encoderContainer.encodeIfPresent(headers, forKey: .headers)
        try encoderContainer.encodeIfPresent(xml, forKey: .xml)
        try encoderContainer.encodeIfPresent(isSuccessful, forKey: .isSuccessful)
    }
}
