//
// DlnaProfileType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum DlnaProfileType: String, Codable, CaseIterable {
    case audio = "Audio"
    case video = "Video"
    case photo = "Photo"
}
