//
// HardwareEncodingType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Enum HardwareEncodingType. */
public enum HardwareEncodingType: String, Codable, CaseIterable {
    case amf = "AMF"
    case qsv = "QSV"
    case nvenc = "NVENC"
    case v4L2M2M = "V4L2M2M"
    case vaapi = "VAAPI"
    case videoToolBox = "VideoToolBox"
}
