//
// HeaderMatchType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum HeaderMatchType: String, Codable, CaseIterable {
    case equals = "Equals"
    case regex = "Regex"
    case substring = "Substring"
}
