//
// ImageSavingConvention.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ImageSavingConvention: String, Codable, CaseIterable {
    case legacy = "Legacy"
    case compatible = "Compatible"
}
