//
// ImageOrientation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ImageOrientation: String, Codable, CaseIterable {
    case topLeft = "TopLeft"
    case topRight = "TopRight"
    case bottomRight = "BottomRight"
    case bottomLeft = "BottomLeft"
    case leftTop = "LeftTop"
    case rightTop = "RightTop"
    case rightBottom = "RightBottom"
    case leftBottom = "LeftBottom"
}
