//
// LibraryOptionsResultDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Library options result dto. */
public struct LibraryOptionsResultDto: Codable, Hashable {

    /** Gets or sets the metadata savers. */
    public var metadataSavers: [LibraryOptionInfoDto]?
    /** Gets or sets the metadata readers. */
    public var metadataReaders: [LibraryOptionInfoDto]?
    /** Gets or sets the subtitle fetchers. */
    public var subtitleFetchers: [LibraryOptionInfoDto]?
    /** Gets or sets the type options. */
    public var typeOptions: [LibraryTypeOptionsDto]?

    public init(metadataSavers: [LibraryOptionInfoDto]? = nil, metadataReaders: [LibraryOptionInfoDto]? = nil, subtitleFetchers: [LibraryOptionInfoDto]? = nil, typeOptions: [LibraryTypeOptionsDto]? = nil) {
        self.metadataSavers = metadataSavers
        self.metadataReaders = metadataReaders
        self.subtitleFetchers = subtitleFetchers
        self.typeOptions = typeOptions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metadataSavers = "MetadataSavers"
        case metadataReaders = "MetadataReaders"
        case subtitleFetchers = "SubtitleFetchers"
        case typeOptions = "TypeOptions"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: CodingKeys.self)
        try encoderContainer.encodeIfPresent(metadataSavers, forKey: .metadataSavers)
        try encoderContainer.encodeIfPresent(metadataReaders, forKey: .metadataReaders)
        try encoderContainer.encodeIfPresent(subtitleFetchers, forKey: .subtitleFetchers)
        try encoderContainer.encodeIfPresent(typeOptions, forKey: .typeOptions)
    }
}
