//
// SubtitleDeliveryMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Delivery method to use during playback of a specific subtitle format. */
public enum SubtitleDeliveryMethod: String, Codable, CaseIterable {
    case encode = "Encode"
    case embed = "Embed"
    case external = "External"
    case hls = "Hls"
    case drop = "Drop"
}
