//
// TransportStreamTimestamp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TransportStreamTimestamp: String, Codable, CaseIterable {
    case _none = "None"
    case zero = "Zero"
    case valid = "Valid"
}
