//
// TunerChannelMapping.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TunerChannelMapping: Codable, Hashable {

    public var name: String?
    public var providerChannelName: String?
    public var providerChannelId: String?
    public var id: String?

    public init(name: String? = nil, providerChannelName: String? = nil, providerChannelId: String? = nil, id: String? = nil) {
        self.name = name
        self.providerChannelName = providerChannelName
        self.providerChannelId = providerChannelId
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case providerChannelName = "ProviderChannelName"
        case providerChannelId = "ProviderChannelId"
        case id = "Id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: CodingKeys.self)
        try encoderContainer.encodeIfPresent(name, forKey: .name)
        try encoderContainer.encodeIfPresent(providerChannelName, forKey: .providerChannelName)
        try encoderContainer.encodeIfPresent(providerChannelId, forKey: .providerChannelId)
        try encoderContainer.encodeIfPresent(id, forKey: .id)
    }
}
