//
// GroupShuffleMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Enum GroupShuffleMode. */
public enum GroupShuffleMode: String, Codable, CaseIterable {
    case sorted = "Sorted"
    case shuffle = "Shuffle"
}
