// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public enum DayPattern: String, Codable, CaseIterable {
    case daily = "Daily"
    case weekdays = "Weekdays"
    case weekends = "Weekends"
}
