//
// jellyfin-sdk-swift is subject to the terms of the Mozilla Public
// License, v2.0. If a copy of the MPL was not distributed with this
// file, you can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2025 Jellyfin & Jellyfin Contributors
//

import Foundation

/// Used to control the data that gets attached to DtoBaseItems.
public enum ItemFields: String, Codable, CaseIterable {
    case airTime = "AirTime"
    case canDelete = "CanDelete"
    case canDownload = "CanDownload"
    case channelInfo = "ChannelInfo"
    case chapters = "Chapters"
    case trickplay = "Trickplay"
    case childCount = "ChildCount"
    case cumulativeRunTimeTicks = "CumulativeRunTimeTicks"
    case customRating = "CustomRating"
    case dateCreated = "DateCreated"
    case dateLastMediaAdded = "DateLastMediaAdded"
    case displayPreferencesID = "DisplayPreferencesId"
    case etag = "Etag"
    case externalURLs = "ExternalUrls"
    case genres = "Genres"
    case homePageURL = "HomePageUrl"
    case itemCounts = "ItemCounts"
    case mediaSourceCount = "MediaSourceCount"
    case mediaSources = "MediaSources"
    case originalTitle = "OriginalTitle"
    case overview = "Overview"
    case parentID = "ParentId"
    case path = "Path"
    case people = "People"
    case playAccess = "PlayAccess"
    case productionLocations = "ProductionLocations"
    case providerIDs = "ProviderIds"
    case primaryImageAspectRatio = "PrimaryImageAspectRatio"
    case recursiveItemCount = "RecursiveItemCount"
    case settings = "Settings"
    case screenshotImageTags = "ScreenshotImageTags"
    case seriesPrimaryImage = "SeriesPrimaryImage"
    case seriesStudio = "SeriesStudio"
    case sortName = "SortName"
    case specialEpisodeNumbers = "SpecialEpisodeNumbers"
    case studios = "Studios"
    case taglines = "Taglines"
    case tags = "Tags"
    case remoteTrailers = "RemoteTrailers"
    case mediaStreams = "MediaStreams"
    case seasonUserData = "SeasonUserData"
    case serviceName = "ServiceName"
    case themeSongIDs = "ThemeSongIds"
    case themeVideoIDs = "ThemeVideoIds"
    case externalEtag = "ExternalEtag"
    case presentationUniqueKey = "PresentationUniqueKey"
    case inheritedParentalRatingValue = "InheritedParentalRatingValue"
    case externalSeriesID = "ExternalSeriesId"
    case seriesPresentationUniqueKey = "SeriesPresentationUniqueKey"
    case dateLastRefreshed = "DateLastRefreshed"
    case dateLastSaved = "DateLastSaved"
    case refreshState = "RefreshState"
    case channelImage = "ChannelImage"
    case enableMediaSourceDisplay = "EnableMediaSourceDisplay"
    case width = "Width"
    case height = "Height"
    case extraIDs = "ExtraIds"
    case localTrailerCount = "LocalTrailerCount"
    case isHD = "IsHD"
    case specialFeatureCount = "SpecialFeatureCount"
}
