// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public enum LogLevel: String, Codable, CaseIterable {
    case trace = "Trace"
    case debug = "Debug"
    case information = "Information"
    case warning = "Warning"
    case error = "Error"
    case critical = "Critical"
    case `none` = "None"
}
