// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct MetadataConfiguration: Codable {
    public var useFileCreationTimeForDateAdded: Bool?

    public init(useFileCreationTimeForDateAdded: Bool? = nil) {
        self.useFileCreationTimeForDateAdded = useFileCreationTimeForDateAdded
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.useFileCreationTimeForDateAdded = try values.decodeIfPresent(Bool.self, forKey: "UseFileCreationTimeForDateAdded")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(useFileCreationTimeForDateAdded, forKey: "UseFileCreationTimeForDateAdded")
    }
}
