module: JellyfinAPI

generate:
  - entities
  - paths

dataTypes:
  integer:
    int32: Int
    int64: Int
  string:
    uuid: String

entities:
  automaticIdentifiable: true
  conformances:
    - Codable
    - Hashable
    - Sendable
  enumConformances:
    - Codable
    - CaseIterable
    - Sendable
  indirectProperties:
    - RemoteSearchResult.albumArtist
    - BaseItemDto.currentProgram
  sortProperties: true

paths:
  filenameTemplate: "%0API.swift"

rename:
  enumCases:
    VideoRangeType.DOVI: dovi
    VideoRangeType.DOVIWithHDR10: doviWithHDR10
    VideoRangeType.DOVIWithHLG: doviWithHLG
    VideoRangeType.DOVIWithSDR: doviWithSDR
    VideoRangeType.DOVIWithEL: doviWithEL
    VideoRangeType.DOVIWithHDR10Plus: doviWithHDR10Plus
    VideoRangeType.DOVIWithELHDR10Plus: doviWithELHDR10Plus
    VideoRangeType.DOVIInvalid: doviInvalid
    VideoRangeType.HDR10Plus: hdr10Plus
