//
// InstallationInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Class InstallationInfo. */
public struct InstallationInfo: Codable, Hashable {

    /** Gets or sets the Id. */
    public var guid: UUID?
    /** Gets or sets the name. */
    public var name: String?
    /** Gets or sets the version. */
    public var version: Version?
    /** Gets or sets the changelog for this version. */
    public var changelog: String?
    /** Gets or sets the source URL. */
    public var sourceUrl: String?
    /** Gets or sets a checksum for the binary. */
    public var checksum: String?
    /** Gets or sets package information for the installation. */
    public var packageInfo: PackageInfo?

    public init(guid: UUID? = nil, name: String? = nil, version: Version? = nil, changelog: String? = nil, sourceUrl: String? = nil, checksum: String? = nil, packageInfo: PackageInfo? = nil) {
        self.guid = guid
        self.name = name
        self.version = version
        self.changelog = changelog
        self.sourceUrl = sourceUrl
        self.checksum = checksum
        self.packageInfo = packageInfo
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case guid = "Guid"
        case name = "Name"
        case version = "Version"
        case changelog = "Changelog"
        case sourceUrl = "SourceUrl"
        case checksum = "Checksum"
        case packageInfo = "PackageInfo"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(guid, forKey: .guid)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(changelog, forKey: .changelog)
        try container.encodeIfPresent(sourceUrl, forKey: .sourceUrl)
        try container.encodeIfPresent(checksum, forKey: .checksum)
        try container.encodeIfPresent(packageInfo, forKey: .packageInfo)
    }



}
