//
// LiveTvServiceStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum LiveTvServiceStatus: String, Codable, CaseIterable {
    case ok = "Ok"
    case unavailable = "Unavailable"
}
