//
// PinRedeemResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct PinRedeemResult: Codable, Hashable {

    /** Gets or sets a value indicating whether this MediaBrowser.Model.Users.PinRedeemResult is success. */
    public var success: Bool?
    /** Gets or sets the users reset. */
    public var usersReset: [String]?

    public init(success: Bool? = nil, usersReset: [String]? = nil) {
        self.success = success
        self.usersReset = usersReset
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success = "Success"
        case usersReset = "UsersReset"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(usersReset, forKey: .usersReset)
    }



}
