//
// ConfigurationPageType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Enum ConfigurationPageType. */
public enum ConfigurationPageType: String, Codable, CaseIterable {
    case pluginConfiguration = "PluginConfiguration"
    case _none = "None"
}
