//
// EncodingContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum EncodingContext: String, Codable, CaseIterable {
    case streaming = "Streaming"
    case _static = "Static"
}
