//
// MediaUpdateInfoDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Media Update Info Dto. */
public struct MediaUpdateInfoDto: Codable, Hashable {

    /** Gets or sets the list of updates. */
    public var updates: [MediaUpdateInfoPathDto]?

    public init(updates: [MediaUpdateInfoPathDto]? = nil) {
        self.updates = updates
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case updates = "Updates"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(updates, forKey: .updates)
    }



}
