//
// MetadataField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Enum MetadataFields. */
public enum MetadataField: String, Codable, CaseIterable {
    case cast = "Cast"
    case genres = "Genres"
    case productionLocations = "ProductionLocations"
    case studios = "Studios"
    case tags = "Tags"
    case name = "Name"
    case overview = "Overview"
    case runtime = "Runtime"
    case officialRating = "OfficialRating"
}
