//
// PingRequestDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Class PingRequestDto. */
public struct PingRequestDto: Codable, Hashable {

    /** Gets or sets the ping time. */
    public var ping: Int64?

    public init(ping: Int64? = nil) {
        self.ping = ping
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ping = "Ping"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ping, forKey: .ping)
    }



}
