//
// PluginSecurityInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Plugin security info. */
public struct PluginSecurityInfo: Codable, Hashable {

    /** Gets or sets the supporter key. */
    public var supporterKey: String?
    /** Gets or sets a value indicating whether is mb supporter. */
    public var isMbSupporter: Bool?

    public init(supporterKey: String? = nil, isMbSupporter: Bool? = nil) {
        self.supporterKey = supporterKey
        self.isMbSupporter = isMbSupporter
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case supporterKey = "SupporterKey"
        case isMbSupporter = "IsMbSupporter"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(supporterKey, forKey: .supporterKey)
        try container.encodeIfPresent(isMbSupporter, forKey: .isMbSupporter)
    }



}
