//
// SeriesStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Enum SeriesStatus. */
public enum SeriesStatus: String, Codable, CaseIterable {
    case continuing = "Continuing"
    case ended = "Ended"
}
