name: Generate Unstable Branch

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: unstable-branch

jobs:
  build:
    runs-on: macos-latest
    if: ${{ github.repository == 'jellyfin/jellyfin-sdk-swift' }}
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4
      with:
        ref: main
        token: ${{ secrets.JF_BOT_TOKEN }}

    - name: Generate API
      run: |
        cd $GITHUB_WORKSPACE
        make update

    - name: Commit changes
      run: |
        git config user.name jellyfin-bot
        git config user.email team@jellyfin.org
        git checkout -B unstable
        git add .
        git commit --allow-empty -m "Update unstable generation"
        git push --force origin openapi-unstable
